# Linux-only symlinks (source:target)
$(pwd)/linux/hypr:$HOME/.config/hypr
$(pwd)/linux/waybar:$HOME/.config/waybar
$(pwd)/linux/wezterm:$HOME/.config/wezterm
$(pwd)/linux/btop:$HOME/.config/btop
$(pwd)/linux/rofi:$HOME/.config/rofi
$(pwd)/linux/systemd/user:$HOME/.config/systemd/user
$(pwd)/linux/swaync:$HOME/.config/swaync
$(pwd)/linux/wireplumber:$HOME/.config/wireplumber
$(pwd)/linux/pipewire:$HOME/.config/pipewire
$(pwd)/linux/gtk-3.0:$HOME/.config/gtk-3.0
$(pwd)/linux/gtk-4.0:$HOME/.config/gtk-4.0
$(pwd)/linux/matugen:$HOME/.config/matugen
$(pwd)/linux/wlogout:$HOME/.config/wlogout
$(pwd)/linux/quick-panel:$HOME/.config/quick-panel
$(pwd)/linux/profile:$HOME/.profile
